### ISSUE TITLE
AppVeyor's new artifacts retention policy

### ISSUE THREAD

**Issue by Radfordhound** [blueskythlikesclouds/TagTools#2]
https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy

TL;DR: AppVeyor now only stores artifacts for 6 months after they were built. After that they're deleted.
Might be a good idea to upload "stable" artifacts as GitHub releases? That way they'll be permanent.

**Comment by blueskythlikesclouds** [comment]
Can't I just rebuild the commit?

**Comment by Radfordhound** [comment]
Yeah I think so, though you'd have to do that every 6 months

**Comment by blueskythlikesclouds** [comment]
I'm fine with that, lol

**Comment by Radfordhound** [comment]
Welp cool then lol

**Comment by ghost** [comment]
Please can you reupload artifacts
