### ISSUE TITLE
Sonic forces stage collision don't convert

### ISSUE THREAD

**Issue by ghost** [blueskythlikesclouds/TagTools#5]
Hello, i tried the converter on a sonic forces stage collision and nothing happen, i have drag and drop the .phy.hkx on CollisionConverter, that normal or it supposed to work ?

**Comment by blueskythlikesclouds** [comment]
Are you trying to backport it to 2012? If you want to do that, you're supposed to drag and drop to TagTools.exe.

**Comment by ghost** [comment]
I have do that, the hkx size change but when i drag and drop it on collisionConverter nothing happen too

**Comment by blueskythlikesclouds** [comment]
You don't need to drag and drop it to CollisionConverter.exe.
Are you trying to convert the collision to FBX? If so, use [this program](https://github.com/blueskythlikesclouds/SkythTools/blob/master/Sonic%20Lost%20World/collision2fbx.exe) after converting with TagTools.exe.

**Comment by ghost** [comment]
thank you so much !
